Load the world from filename defined in the config.
GrizzlT/FalconMC pull request #10
Opened 2022-08-26 10:18 UTC by 0101coding

This is to solve the second issue mentioned in this PR #9

2022-08-26 10:27 UTC, GrizzlT requested changes
Thank you for this pr.

I don't think this approach would solve the issue completely given the use of `unwrap()` which would result in a crash when no world is specified.

Instead, `FalconWorld` is designed to have a dynamic amount of chunks, thus that could also be zero chunks. I think this is the more ideal way of solving the issue: if the config setting is empty, just load a `FalconWorld` with zero chunks.

2022-08-26 10:27 UTC, GrizzlT commented on crates/logic/src/server/network/login.rs
> +            self.world.as_mut().unwrap().send_chunks_for_player(player);
`unwrap` in this case would crash the server when no world is specified, right?

2022-08-26 10:27 UTC, GrizzlT commented on crates/logic/src/server/network/play.rs
> +            self.world.as_mut().unwrap().update_player_pos(self.players.get(&uuid).unwrap(), old_x, old_z, x, z);
same here

2022-08-26 10:27 UTC, GrizzlT commented on crates/logic/src/server/network/play.rs
> +            self.world.as_mut().unwrap().update_view_distance(player, view_distance);
and here

2022-08-26 10:27 UTC, GrizzlT commented on crates/main/src/server/mod.rs
> -    let world = {
This should become a match. (see my review)

2022-08-26 10:40 UTC, 0101coding commented
Ok. Thanks. I will get to that. I thought as much

2022-08-27 00:39 UTC, taylorsk commented
The issue was fixed in PR #9

2022-08-27 00:39 UTC, closed without merging