🔥➖ Remove unnecessary dependency ignore_result
GrizzlT/FalconMC pull request #23
Opened 2022-10-06 11:58 UTC by VixieTSQ

Using `.ok()` on results we do not care about achieves the same effect as using the ignore_result crate. One less dependency to bring down and worry about.

I also believe it reads the same as using ignore_result. `.ok()` as in "this is okay`.

2022-10-06 13:39 UTC, GrizzlT submitted a review, later dismissed
Great work, maybe we should provide some comments explaining why it's okay to ignore the error each time?

2022-10-06 13:41 UTC, VixieTSQ commented
> Great work, maybe we should provide some comments explaining why it's okay to ignore the error each time?

Maybe! But I would have to do a lot of reading as I'm not familiar of why it's okay in any of these instances

2022-10-06 13:46 UTC, VixieTSQ commented
Upon further inspection, alot of these ignores actually have todo comments for them to not be ignored. Maybe I should work on these.

2022-10-06 13:54 UTC, GrizzlT commented
You could try that. Most of the ignores have to do with sending a task to a different thread, what do you think we should do when an error occurs for that?

2022-10-06 13:56 UTC, VixieTSQ commented
> You could try that. Most of the ignores have to do with sending a task to a different thread, what do you think we should do when an error occurs for that?

Where's the receiver? Do you think it might be possible to handle the error on that side?

2022-10-06 13:57 UTC, GrizzlT commented
If the channel errors, would the receiver receive that error?

2022-10-06 14:05 UTC, VixieTSQ commented
> If the channel errors, would the receiver receive that error?

I don't follow. I see here a closure gets sent across a channel, then I assume that closure is ran on the other side of the channel. So we can say that closure returns a result, and the receiver who runs the closure deals with the result.

If the channel itself error, then that would mean the receiver has been dropped, probably because of unwinding. In which case I think it's fine to ignore the error, which you already are doing.

2022-10-06 14:14 UTC, GrizzlT commented
> > If the channel errors, would the receiver receive that error?
> 
> I don't follow. I see here a closure gets sent across a channel, then I assume that closure is ran on the other side of the channel. So we can say that closure returns a result, and the receiver who runs the closure deals with the result.
> 
> If the channel itself errors, then that would mean the receiver has been dropped, probably because of unwinding. In which case I think it's fine to ignore the error, which you already are doing.

Yes, but aren’t most of the ignored errors because of channels that might error on send? The only error I haven’t properly dealt with is the one inside the send function of `FalconConnection` I think

2022-10-06 14:17 UTC, VixieTSQ commented
> > > If the channel errors, would the receiver receive that error?
> > 
> > 
> > I don't follow. I see here a closure gets sent across a channel, then I assume that closure is ran on the other side of the channel. So we can say that closure returns a result, and the receiver who runs the closure deals with the result.
> > If the channel itself errors, then that would mean the receiver has been dropped, probably because of unwinding. In which case I think it's fine to ignore the error, which you already are doing.
> 
> Yes, but aren’t most of the ignored errors because of channels that might error on send? The only error I haven’t properly dealt with is the one inside the send function of `FalconConnection` I think

`FalconConnection` is what I'm currently dealing with. It seems to affect a lot of things. I actually think this is where most of the ignored errors come from. I'll report back when I'm done experimenting

2022-10-06 14:49 UTC, VixieTSQ commented
@GrizzlT Hey! I wasn't really thinking too hard about this new commit. Just experimenting. If what I wrote is non-sense then we can just revert it, otherwise we can refine it.

in `tick.rs` this in particular I'm pretty sure is not what you want
```
if let Err(error) = res {
    self.disconnect(ChatComponent::from_text(format!("Error on task: {}", error), ComponentStyle::with_version(self.state.protocol_id().unsigned_abs())));
};
```
or maybe I got a really lucky guess and it is correct.

2022-10-06 15:51 UTC, GrizzlT requested changes
Looks good to me, lemme know what you think of my suggestions and then we're on to merging again!

2022-10-06 15:51 UTC, GrizzlT commented on crates/logic/src/connection/tick.rs
> +                    };
This feels more intuitive to me.
```suggestion
                    if let Err(err)r = match task {
                        ConnectionTask::Sync(task) => {
                            task(&mut self)
                        }
                        ConnectionTask::Async(task) => {
                            task(&mut self).await
                        }
                    } {
                        self.disconnect(ChatComponent::from_text(format!("Error on task: {}", error), ComponentStyle::with_version(self.state.protocol_id().unsigned_abs())));
                    }
```

2022-10-06 15:51 UTC, GrizzlT commented on crates/logic/src/connection/wrapper.rs
> +                Ok(())
Would this be more concise? (or did I miss something?)
```suggestion
                connection.send_packet(packet, write_fn)
```

2022-10-06 15:51 UTC, GrizzlT commented on crates/logic/src/player/mod.rs
> +            Ok(())
```suggestion
            Ok(())
```

2022-10-06 15:51 UTC, GrizzlT commented on crates/logic/src/player/mod.rs
> +            Ok(())
Wouldn't this be more concise?
```suggestion
            connection.send_packet(elapsed as i64, falcon_send::write_keep_alive)
```

2022-10-06 15:51 UTC, GrizzlT commented on crates/logic/src/server/network/login.rs
> +                .send_packet(LoginSuccessSpec::new(player_uuid, username2), falcon_send::write_login_success)?;
For if formatting allows
```suggestion
            connection.send_packet(LoginSuccessSpec::new(player_uuid, username2), falcon_send::write_login_success)?;
```

2022-10-06 15:51 UTC, GrizzlT commented on crates/logic/src/server/network/login.rs
> +            Ok(())
Either add an empty line after the `send_packet` call or remove it here.
```suggestion
            Ok(())
```

2022-10-06 15:54 UTC, GrizzlT commented on crates/logic/src/server/network/login.rs
> +                .send_packet(LoginSuccessSpec::new(player_uuid, username2), falcon_send::write_login_success)?;
This is weird, handle with care pls

2022-10-06 15:59 UTC, VixieTSQ commented on crates/logic/src/connection/wrapper.rs
> +                Ok(())
The `?` does some error conversion stuff here. It is necessary.

2022-10-06 16:00 UTC, VixieTSQ commented on crates/logic/src/player/mod.rs
> +            Ok(())
The `?` does some error conversion stuff here. It is necessary.

2022-10-06 16:13 UTC, GrizzlT commented on crates/logic/src/connection/wrapper.rs
> +                Ok(())
And what about
```suggestion
                Ok(connection.send_packet(packet, write_fn)?)
```
?

2022-10-06 16:13 UTC, GrizzlT commented on crates/logic/src/player/mod.rs
> +            Ok(())
Same here?
```suggestion
            Ok(connection.send_packet(elapsed as i64, falcon_send::write_keep_alive)?)
```

2022-10-06 16:21 UTC, VixieTSQ commented on crates/logic/src/connection/wrapper.rs
> +                Ok(())
That would technically work, but it feels convoluted. Using the () specifically returned from that method feels weird.

2022-10-06 16:23 UTC, GrizzlT commented on crates/logic/src/connection/wrapper.rs
> +                Ok(())
Really? I like how it makes everything one line instead of multiple. What exactly feels weird about it?

2022-10-09 06:21 UTC, GrizzlT approved these changes

2022-10-09 06:23 UTC, merged